### ISSUE TITLE
add warning to install missing ffmpeg

### ISSUE THREAD

**Issue by jfalxa** [internet4000/r4#4]
When using `r4 play detecteve` it should warn that `ffmpeg` is missing the same way it warns that `youtube-dl` is missing.

**Comment by oskarrough** [comment]
Hm yes. Why do we need ffmpeg again?

**Comment by hugurp** [comment]
`r4 play channel-slug`

**Comment by oskarrough** [comment]
related to this, can we rewrite so you don't need external dependencies?

> My *hottest* take of the week: rewrite all your CLIs in Go, Rust, Haskell, OCaml… doesn’t matter which; just make it something that has a statically-compiled binary you can distribute (no runtime required), and which understands UTF-8 out of the box. (https://mobile.twitter.com/chriskrycho/status/1125403786321596416)

**Comment by hugurp** [comment]
agreeing. But we'll need external dependencies probably, like ffmpeg and stuff?

**Comment by hugurp** [comment]
closed because this app does no more playing, see #7
